# Scheduling the function dailyemail to run every 5 minutes.
# [functions."dailyemail-background"]
# schedule = "*/5 * * * *"

# Fixing the bug of page reload on prod throwing a 404 error
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200